apiVersion: v1
entries:
  jetic-bridge:
  - apiVersion: v2
    appVersion: 0.25.0
    created: "2022-08-03T13:47:07.7620604+03:00"
    description: A Helm chart for connecting your Kubernetes cluster to the Jetic
      Platform
    digest: 3b80a9a00e9bc3d572737d9663f65358de566fc65af7ebf839527fe41bb90438
    icon: https://app.jetic.io/favicon.ico
    name: jetic-bridge
    type: application
    urls:
    - https://datagreat.github.io/jetic-bridge/charts/jetic-bridge-1.9.0.tgz
    version: 1.9.0
  - apiVersion: v2
    appVersion: 0.19.0
    created: "2022-08-03T13:47:07.7620604+03:00"
    description: A Helm chart for connecting your Kubernetes cluster to the Jetic
      Platform
    digest: c5441882b30a4e373d17d5b98b536137559e404d4b938b89b3d5c290461cd8d0
    icon: https://app.jetic.io/favicon.ico
    name: jetic-bridge
    type: application
    urls:
    - https://datagreat.github.io/jetic-bridge/charts/jetic-bridge-1.6.0.tgz
    version: 1.6.0
  - apiVersion: v2
    appVersion: 0.16.4
    created: "2022-08-03T13:47:07.7610595+03:00"
    description: A Helm chart for connecting your Kubernetes cluster to the Jetic
      Platform
    digest: c47441a15f039b88d519c2f18e7f02917404297d2430820b0ba0ded9507443d1
    icon: https://app.jetic.io/favicon.ico
    name: jetic-bridge
    type: application
    urls:
    - https://datagreat.github.io/jetic-bridge/charts/jetic-bridge-1.5.0.tgz
    version: 1.5.0
  - apiVersion: v2
    appVersion: 0.16.4
    created: "2022-08-03T13:47:07.760559+03:00"
    dependencies:
    - name: camel-k
      repository: https://apache.github.io/camel-k/charts
      version: 0.7.1
    description: A Helm chart for connecting your Kubernetes cluster to the Jetic
      Platform
    digest: 1689104df438a564a69b47e68e7c6250a0191fefa660785e54b9e480b857e7aa
    icon: https://app.jetic.io/favicon.ico
    name: jetic-bridge
    type: application
    urls:
    - https://datagreat.github.io/jetic-bridge/charts/jetic-bridge-1.4.0.tgz
    version: 1.4.0
  - apiVersion: v2
    appVersion: 0.16.2
    created: "2022-08-03T13:47:07.7555547+03:00"
    description: A Helm chart for connecting your Kubernetes cluster to the Jetic
      Platform
    digest: 64ccf52292ce293373d8550b808a06ff0905f98610b1d88a5844be34fb2a08e8
    icon: https://app.jetic.io/favicon.ico
    name: jetic-bridge
    type: application
    urls:
    - https://datagreat.github.io/jetic-bridge/charts/jetic-bridge-1.3.2.tgz
    version: 1.3.2
  - apiVersion: v2
    appVersion: 0.16.2
    created: "2022-08-03T13:47:07.7550543+03:00"
    description: A Helm chart for connecting your Kubernetes cluster to the Jetic
      Platform
    digest: 7a753963e36137a8cda4767a3a6524ac99178176f9a0405020ebc15d4ddc8a6e
    icon: https://app.jetic.io/favicon.ico
    name: jetic-bridge
    type: application
    urls:
    - https://datagreat.github.io/jetic-bridge/charts/jetic-bridge-1.3.1.tgz
    version: 1.3.1
  - apiVersion: v2
    appVersion: 0.16.2
    created: "2022-08-03T13:47:07.7545539+03:00"
    description: A Helm chart for connecting your Kubernetes cluster to the Jetic
      Platform
    digest: 214979eb200521fe09606fd21081d9c4d41bf8e573acef96cca9a8b63a329245
    icon: https://app.jetic.io/static/media/jetic-logo.55b8bab9.svg
    name: jetic-bridge
    type: application
    urls:
    - https://datagreat.github.io/jetic-bridge/charts/jetic-bridge-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-08-03T13:47:07.7540536+03:00"
    description: A Helm chart for connecting your Kubernetes cluster to the Jetic
      Platform
    digest: 30da19501e9b82fb7bae9c3284d3bb6e8759b505008c8bf14c92afe3f23a2d4c
    name: jetic-bridge
    type: application
    urls:
    - https://datagreat.github.io/jetic-bridge/charts/jetic-bridge-1.2.tgz
    version: "1.2"
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-08-03T13:47:07.7535533+03:00"
    description: A Helm chart for connecting your Kubernetes cluster to the Jetic
      Platform
    digest: 076377464a65512dbbb026fa657334b670b625fec6c6320f297b117f220303cd
    name: jetic-bridge
    type: application
    urls:
    - https://datagreat.github.io/jetic-bridge/charts/jetic-bridge-1.1.tgz
    version: "1.1"
generated: "2022-08-03T13:47:07.7485489+03:00"
